# --- Main Colors ---
background            #18120b
foreground            #ede0d4
cursor                #ede0d4
cursor_text_color     #18120b

selection_background  #56432b
selection_foreground  #fbdebc

url_color             #b9cda0

# --- ANSI Colors ---
color0                #18120b
color1                #ffb4ab
color2                #b9cda0
color3                #ddc2a1
color4                #f5bc6f
color5                #b9cda0
color6                #ddc2a1
color7                #ede0d4

color8                #4f4539
color9                #93000a
color10               #3b4c29
color11               #56432b
color12               #633f00
color13               #56432b
color14               #3b4c29
color15               #d3c4b4

# --- Starship Prompt Bubbles ---
color255              #633f00
color254              #f5bc6f
color253              #56432b
color252              #ddc2a1
color251              #3b4c29
color250              #b9cda0
color249              #93000a
color248              #ffb4ab

color232              #ffddb4
color233              #452b00
color234              #fbdebc
color235              #3e2d16
color236              #d4eabb
color237              #253515
color238              #ffdad6
color239              #690005
color240              #ffddb4

# Matched with unthemed light/dark
color243              #f5bc6f
color244              #ffb4ab
color245              #4f4539

# --- UI Elements ---
active_tab_foreground   #452b00
active_tab_background   #f5bc6f
inactive_tab_foreground #ffddb4
inactive_tab_background #633f00

active_border_color     #f5bc6f
inactive_border_color   #9c8f80

# --- Marks ---
mark1_foreground        #291800
mark1_background        #ffddb4
mark2_foreground        #271904
mark2_background        #fbdebc
mark3_foreground        #101f03
mark3_background        #d4eabb
